; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TBI Serial Agent"
#define MyAppVersion "0.8"
#define MyAppPublisher "Teknik Bilgi İşlem"
#define MyAppURL "http://www.teknikbilgiislem.com.tr/"
#define MyAppExeName "tbi_serial_agent.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E90CA1C0-C6A8-49FD-9562-63D680796373}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\TBI/Serial Agent
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\msi\PycharmProjects\tbi_serial_agent\dist
OutputBaseFilename=TBI Service Agent Installer
SetupIconFile=C:\Users\msi\PycharmProjects\tbi_serial_agent\app.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\msi\PycharmProjects\tbi_serial_agent\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\msi\PycharmProjects\tbi_serial_agent\dist\error.log"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Users\msi\PycharmProjects\tbi_serial_agent\dist\scripts.tsc"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Users\mehme\Desktop\repos\tbi\tbi_serial_agent\ui\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\msi\PycharmProjects\tbi_serial_agent\app.ico"; DestDir: "{app}"; Flags: ignoreversion 
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Setup]
PrivilegesRequired=admin

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: runascurrentuser nowait postinstall skipifsilent

